#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: $(date)

pkill -f -9 mpvpaper

nohup mpvpaper -p -a MAX -o "no-audio loop hwdec=auto-safe really-quiet panscan=1.0 scale=bilinear cscale=bilinear dscale=bilinear correct-downscaling=no sigmoid-upscaling=no load-scripts=no no-sub no-osd-bar osd-level=0 stop-screensaver=no framedrop=vo opengl-pbo=yes interpolation=no video-sync=audio" ALL "/home/medhansh/Pictures/wallpapers/animated/scenery/blue-moon-ocean-night-moewalls-com.mp4" >/dev/null 2>&1 &
