-- Generated by nwg-displays on 2026-08-18 at 13:04:54. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@165.0",
    position = "1920x80",
    scale = 1.6,
    bitdepth = 10
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "0x0",
    scale = 1.0,
    bitdepth = 8
})
