preload = /home/medhansh/Pictures/walpapers/geminiHere/pink/a_sword_with_flowers_on_it.jpg
wallpaper = eDP-1,/home/medhansh/Pictures/walpapers/geminiHere/pink/a_sword_with_flowers_on_it.jpg
wallpaper = HDMI-A-1,/home/medhansh/Pictures/walpapers/geminiHere/pink/a_sword_with_flowers_on_it.jpg
