Gdk/UnscaledDPI 147456
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout ":"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gtk/CursorThemeSize 48
Net/SoundThemeName "freedesktop"
Gtk/FontName "Google Sans Flex, Medium 11"
Net/ThemeName "adw-gtk3-dark"
Net/IconThemeName "YAMIS"
Gtk/CursorThemeName "Bibata-Modern-Classic"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
