return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    config = function()
        local wk = require("which-key")

        wk.setup({
            delay = 300,
            preset = "classic",
        })

        wk.add({
            { "<leader>b", desc = "File sidebar" },

            { "<leader>f", group = "Find and format" },
            { "<leader>fs", desc = "Save the current file" },
            { "<leader>ff", desc = "Find a file by name" },
            { "<leader>fg", desc = "Search for text in the project" },
            { "<leader>fb", desc = "Switch between open files" },
            { "<leader>fe", desc = "Open the classic netrw file list" },
            { "<leader>fk", desc = "Browse every keybinding" },
            { "<leader>ft", desc = "Find every TODO, NOTE, or FIX comment" },

            { "<leader>m", group = "Markdown" },
            { "<leader>mp", desc = "Open or close the markdown browser preview" },
            { "<leader>mo", desc = "Open the document or code outline" },
            { "<leader>mn", desc = "Open outline navigation in a floating picker" },
            { "<leader>mr", desc = "Fix markdown list numbering" },

            { "<leader>g", group = "Git" },
            { "<leader>gg", desc = "Open the full git panel" },
            { "<leader>gc", desc = "Start a git commit" },

            { "<leader>h", group = "Git changes" },
            { "<leader>hs", desc = "Stage this changed block" },
            { "<leader>hr", desc = "Discard this changed block" },
            { "<leader>hb", desc = "Show who changed this line and when" },
            { "<leader>hd", desc = "Preview this changed block" },

            { "<leader>r", desc = "Run the current file" },
            { "<leader>q", desc = "Quit the current window" },
            { "<leader>rn", desc = "Rename this symbol everywhere" },

            { "<leader>a", desc = "Save this file in the quick access list" },

            { "<leader>c", group = "Code actions" },
            { "<leader>ca", desc = "Show suggested code fixes and actions" },
            { "<leader>cm", desc = "Open the tool installer" },

            { "<leader>d", group = "Debug and diagnostics" },
            { "<leader>ds", desc = "Explain the problem on this line" },
            { "<leader>db", desc = "Add or remove a breakpoint" },
            { "<leader>dc", desc = "Start or continue debugging" },
            { "<leader>di", desc = "Debug: step into" },
            { "<leader>do", desc = "Debug: step over" },
            { "<leader>dO", desc = "Debug: step out" },
            { "<leader>dr", desc = "Open the debugger console" },
            { "<leader>du", desc = "Open the debugger panels" },
            { "<leader>dt", desc = "Stop debugging" },

            { "<leader>l", desc = "Turn language features on or off" },
            { "<leader>ld", desc = "Jump to where this symbol is defined" },
            { "<leader>lr", desc = "Show every place this symbol is used" },
            { "<leader>li", desc = "Jump to the implementation" },
            { "<leader>lh", desc = "Show documentation for the symbol under the cursor" },
            { "<leader>p", desc = "Open the command palette" },
            { "<leader>b", group = "Buffers and sidebar" },
            { "<leader>bn", desc = "Go to the next open tab" },
            { "<leader>bp", desc = "Go to the previous open tab" },
            { "<leader>u", group = "User interface" },
            { "<leader>ua", desc = "Turn autosave on or off" },
            { "<leader>ub", desc = "Turn autosave on or off for this file" },
            { "<leader>ut", desc = "Choose a theme" },
            { "<leader>un", desc = "Switch to the next theme" },
            { "<leader>up", desc = "Switch to the previous theme" },
            { "<leader>uy", desc = "Turn transparency on or off" },
            { "<leader>w", group = "Workspace sessions" },
            { "<leader>wr", desc = "Restore the saved session for this folder" },
            { "<leader>ws", desc = "Save the current session for this folder" },
            { "<leader>t", group = "Tasks" },
            { "<leader>to", desc = "Open or close the floating terminal" },
            { "<leader>tt", desc = "Open or close the task list" },
            { "<leader>tr", desc = "Choose and run a project task" },
            { "<leader>ta", desc = "Run a task action on the current item" },
            { "<leader>tl", desc = "Load saved task runs" },
            { "<leader>r", group = "Run" },
            { "<leader>rr", desc = "Run the current file" },
            { "<leader>s", group = "Search and jump" },
            { "<leader>sj", desc = "Jump quickly to any visible text" },
            { "<leader>ss", desc = "Jump by syntax block" },
            { "<leader>x", desc = "Close the current tab" },
            { "<leader>z", desc = "Hide coding noise for free-form writing" },
            { "<leader>zz", desc = "Focus on writing or reading without distractions" },
            { "<leader>zw", desc = "Toggle low-noise writing mode for this buffer" },
            { "<leader>zt", desc = "Dim unfocused text around the cursor" },
            { "<leader>?", desc = "Browse every keybinding" },

            { "<leader>xx", desc = "Open the project problem list" },
            { "<leader>xd", desc = "Open the current file problem list" },
            { "<leader>xq", desc = "Open the quickfix list" },
            { "<leader>xl", desc = "Open the location list" },
            { "<leader>hn", desc = "Go to the next git change" },
            { "<leader>hp", desc = "Go to the previous git change" },
            { "<leader>d9", desc = "Add or remove a breakpoint" },
            { "<leader>d0", desc = "Debug: step over" },
            { "<leader>d1", desc = "Debug: step into" },
            { "<leader>d2", desc = "Debug: step out" },
        })
    end,
}
