return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    config = function()
        local wk = require("which-key")

        wk.setup({
            delay = 300,
            preset = "classic",
        })

        wk.add({
            { "<leader>a", desc = "Save this file in the quick access list" },
            { "<leader>e", desc = "Open or close the file sidebar" },
            { "<leader>E", desc = "Open or close the file sidebar" },
            { "<leader>b", group = "Buffers" },
            { "<leader>bb", desc = "Browse open buffers" },
            { "<leader>bd", desc = "Delete the current buffer" },
            { "<leader>bn", desc = "Go to the next buffer" },
            { "<leader>bo", desc = "Delete every other buffer" },
            { "<leader>bp", desc = "Go to the previous buffer" },

            { "<leader>c", group = "Code and tools" },
            { "<leader>ca", desc = "Show suggested code fixes and actions" },
            { "<leader>cf", desc = "Format the current file" },
            { "<leader>cj", desc = "Split or join the current code block" },
            { "<leader>cl", desc = "Turn language features on or off" },
            { "<leader>cm", desc = "Open the tool installer" },

            { "<leader>d", group = "Debug and diagnostics" },
            { "<leader>d0", desc = "Debug: step over" },
            { "<leader>d1", desc = "Debug: step into" },
            { "<leader>d2", desc = "Debug: step out" },
            { "<leader>d9", desc = "Add or remove a breakpoint" },
            { "<leader>db", desc = "Add or remove a breakpoint" },
            { "<leader>dc", desc = "Start or continue debugging" },
            { "<leader>di", desc = "Debug: step into" },
            { "<leader>do", desc = "Debug: step over" },
            { "<leader>dO", desc = "Debug: step out" },
            { "<leader>dr", desc = "Open the debugger console" },
            { "<leader>ds", desc = "Explain the problem on this line" },
            { "<leader>dt", desc = "Stop debugging" },
            { "<leader>du", desc = "Open the debugger panels" },

            { "<leader>f", group = "Files, find, and folds" },
            { "<leader>fM", desc = "Close every fold in the file" },
            { "<leader>fR", desc = "Open every fold in the file" },
            { "<leader>fa", desc = "Toggle the fold under the cursor" },
            { "<leader>fb", desc = "Switch between open files" },
            { "<leader>fc", desc = "Close the fold under the cursor completely" },
            { "<leader>fe", desc = "Open the classic netrw file list" },
            { "<leader>ff", desc = "Find a file by name" },
            { "<leader>fg", desc = "Search for text in the project" },
            { "<leader>fk", desc = "Browse every keybinding" },
            { "<leader>fo", desc = "Open the fold under the cursor completely" },
            { "<leader>fp", desc = "Find a tracked project file" },
            { "<leader>fr", desc = "Reopen a recent file" },
            { "<leader>fs", desc = "Save the current file" },
            { "<leader>ft", desc = "Find every TODO, NOTE, or FIX comment" },
            { "<leader>fv", desc = "Preview folded lines under the cursor" },

            { "<leader>g", group = "Git" },
            { "<leader>gc", desc = "Start a git commit" },
            { "<leader>gg", desc = "Open the full git panel" },

            { "<leader>h", group = "Git changes" },
            { "<leader>hb", desc = "Show who changed this line and when" },
            { "<leader>hd", desc = "Preview this changed block" },
            { "<leader>hD", desc = "Compare this file against git" },
            { "<leader>hn", desc = "Go to the next git change" },
            { "<leader>hp", desc = "Go to the previous git change" },
            { "<leader>hr", desc = "Discard this changed block" },
            { "<leader>hs", desc = "Stage this changed block" },
            { "<leader>hu", desc = "Undo staging for this changed block" },

            { "<leader>lD", desc = "Jump to where this symbol is declared" },
            { "<leader>ld", desc = "Jump to where this symbol is defined" },
            { "<leader>le", desc = "Explain the problem on this line" },
            { "<leader>lh", desc = "Show documentation for the symbol under the cursor" },
            { "<leader>lI", desc = "Turn inlay hints on or off" },
            { "<leader>li", desc = "Jump to the implementation" },
            { "<leader>lk", desc = "Show function signature help" },
            { "<leader>lo", desc = "Search symbols in this file" },
            { "<leader>lR", desc = "Restart language servers for this file" },
            { "<leader>lr", desc = "Show every place this symbol is used" },
            { "<leader>ls", desc = "Search workspace symbols" },
            { "<leader>lt", desc = "Jump to the type definition" },

            { "<leader>m", group = "Markdown and multicursor" },
            { "<leader>mA", desc = "Add cursors for every match in the file" },
            { "<leader>ma", desc = "Add the next matching cursor" },
            { "<leader>mn", desc = "Open outline navigation in a floating picker" },
            { "<leader>mo", desc = "Open the document or code outline" },
            { "<leader>mp", desc = "Open or close the markdown browser preview" },
            { "<leader>mr", desc = "Fix markdown list numbering" },
            { "<leader>ms", desc = "Skip the next matching cursor" },
            { "<leader>mv", desc = "Restore the last cleared multicursor set" },
            { "<leader>mx", desc = "Delete current multicursor" },

            { "<leader>p", desc = "Open the command palette" },

            { "<leader>q", desc = "Quit the current window" },

            { "<leader>rn", desc = "Rename this symbol everywhere" },
            { "<leader>rr", desc = "Run the current file" },
            { "<leader>/", desc = "Toggle line comment" },

            { "<leader>s", group = "Search and jump" },
            { "<leader>sj", desc = "Jump quickly to any visible text" },
            { "<leader>sB", desc = "Search and replace only in the current file" },
            { "<leader>sr", desc = "Search and replace across the project" },
            { "<leader>ss", desc = "Jump by syntax block" },
            { "<leader>sw", desc = "Search for the word under the cursor across the project" },

            { "<leader>t", group = "Terminal and tasks" },
            { "<leader>ta", desc = "Run a task action on the current item" },
            { "<leader>tl", desc = "Load saved task runs" },
            { "<leader>to", desc = "Open or close the floating terminal" },
            { "<leader>tr", desc = "Choose and run a project task" },
            { "<leader>tt", desc = "Open or close the task list" },

            { "<leader>u", group = "UI and theme" },
            { "<leader>ua", desc = "Turn autosave on or off" },
            { "<leader>ub", desc = "Turn autosave on or off for this file" },
            { "<leader>un", desc = "Switch to the next theme" },
            { "<leader>up", desc = "Switch to the previous theme" },
            { "<leader>ut", desc = "Choose a theme" },
            { "<leader>uy", desc = "Turn transparency on or off" },
            { "<leader>uz", desc = "Hide coding noise for free-form writing" },

            { "<leader>w", group = "Windows and sessions" },
            { "<leader>wc", desc = "Close the current window" },
            { "<leader>wh", desc = "Split the window horizontally" },
            { "<leader>wo", desc = "Keep only the current window" },
            { "<leader>wr", desc = "Restore session for cwd" },
            { "<leader>ws", desc = "Save session for auto session root dir" },
            { "<leader>wv", desc = "Split the window vertically" },

            { "<leader>xd", desc = "Open the current file problem list" },
            { "<leader>xl", desc = "Open the location list" },
            { "<leader>xo", desc = "Open document symbols in a side list" },
            { "<leader>xq", desc = "Open the quickfix list" },
            { "<leader>xx", desc = "Open the project problem list" },

            { "<leader>zt", desc = "Dim unfocused text around the cursor" },
            { "<leader>zw", desc = "Toggle low-noise writing mode for this buffer" },
            { "<leader>zz", desc = "Focus on writing or reading without distractions" },

            { "<leader>?", desc = "Browse every keybinding" },
            { "gD", desc = "Jump to where this symbol is declared" },
            { "<C-A-Up>", desc = "Add cursor above" },
            { "<C-A-Down>", desc = "Add cursor below" },
            { "<C-M-Up>", desc = "Add cursor above" },
            { "<C-M-Down>", desc = "Add cursor below" },
            { "<M-LeftMouse>", desc = "Add cursor at clicked position" },
            { "<C-q>", desc = "Toggle multicursor for current match" },
            { "<C-.>", desc = "Snippet: cycle choices", mode = { "i", "s" } },
            { "<C-l>", desc = "Snippet: expand or jump forward", mode = { "i", "s" } },
            { "<C-j>", desc = "Snippet: jump backward", mode = { "i", "s" } },
            { "[b", desc = "Go to the previous open buffer" },
            { "]b", desc = "Go to the next open buffer" },
            { "[d", desc = "Go to the previous diagnostic" },
            { "]d", desc = "Go to the next diagnostic" },
        })
    end,
}
